name: Auto Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "Automated Update"
          git push origin main
